# Exercise_4.09_Tasks - Part 1

1 - Download the customer data set and add it to your “Original Data” folder.

2 - Create a new notebook in your “Scripts” folder for part 1 of this task.

3 - Import your analysis libraries, as well as your new customer data set as a dataframe.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [4]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis'

In [6]:
# Importing data-frame Customers
df_customers=pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/customers.csv')

In [8]:
# Preview the newly imported dataframe
df_customers.head(10)

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374
5,133128,Cynthia,Noble,Female,Kentucky,43,1/1/2017,2,married,49643
6,152052,Chris,Walton,Male,Montana,20,1/1/2017,0,single,61746
7,168851,Joseph,Hickman,Male,South Carolina,30,1/1/2017,0,single,63712
8,69965,Jeremy,Vang,Male,Texas,47,1/1/2017,1,married,162432
9,82820,Shawn,Chung,Male,Virginia,26,1/1/2017,2,married,32072

In [10]:
# Check the dimensions of the dataframe
df_customers.shape

(206209, 10)

In [12]:
# checking descriptive statistics of the data-frame
df_customers.describe()

             user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In [14]:
# Check data types of teh data-frame
df_customers.dtypes

user_id          int64
First Name      object
Surnam          object
Gender          object
STATE           object
Age              int64
date_joined     object
n_dependants     int64
fam_status      object
income           int64
dtype: object

4 - Wrangle the data so that it follows consistent logic; for example, rename columns with illogical names and drop columns that don’t add anything to your analysis.

In [17]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'First Name' : 'first_name'}, inplace = True)

In [19]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'Surnam' : 'last_name'}, inplace = True)

In [21]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'STATE' : 'state'}, inplace = True)

In [23]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'Gender' : 'gender'}, inplace = True)

In [25]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'Age' : 'age'}, inplace = True)

In [27]:
# Rename the columns to establish uniformity
df_customers.rename(columns = {'fam_status' : 'marital_status'}, inplace = True)

In [29]:
# Retrieve the list of column names from data-frame
column_names=list(df_customers)

In [31]:
print(column_names)

['user_id', 'first_name', 'last_name', 'gender', 'state', 'age', 'date_joined', 'n_dependants', 'marital_status', 'income']

The columns containing illogical names have been successfully renamed and are now uniform and clear.
Regarding dropping columns, I think analysis for each of these columns is possible and effective.
So it is not necessary to drop any column.

5 - Complete the fundamental data quality and consistency checks you’ve learned throughout this Achievement; for example, check for and address missing values and duplicates, and convert any mixed-type data.

In [35]:
# Checking for mixed data-types in each column
for col in df_customers.columns:
    # Compare the type of each value in the column to the type of the first value
    weird = (df_customers[col].map(type) != type(df_customers[col].iloc[0]))
    if weird.any():
        print(col)

user_id
first_name
age
n_dependants
income

In [37]:
# The output revealed that the column 'user_id' has mixed data-types that need to be addressed
df_customers['user_id'] = df_customers['user_id'].astype('Int64')

In [39]:
# The output revealed that the column 'first_name' has mixed data-types that need to be addressed
df_customers['first_name'] = df_customers['first_name'].astype(str)

In [41]:
# The output revealed that the column 'age' has mixed data-types that need to be addressed
df_customers['age'] = df_customers['age'].astype('Int64')

In [43]:
# The output revealed that the column 'n_dependants' has mixed data-types that need to be addressed
df_customers['n_dependants'] = df_customers['n_dependants'].astype('Int64')

In [45]:
# The output revealed that the column 'income' has mixed data-types that need to be addressed
df_customers['income'] = df_customers['income'].astype('Int64')

In [47]:
# Re-check the data-types in the data frame and for mixed data-types
df_customers.dtypes

user_id            Int64
first_name        object
last_name         object
gender            object
state             object
age                Int64
date_joined       object
n_dependants       Int64
marital_status    object
income             Int64
dtype: object

In [49]:
# All columns have the appropriate data-types.

In [51]:
# Check for missing data
df_customers.isnull().sum()

user_id           0
first_name        0
last_name         0
gender            0
state             0
age               0
date_joined       0
n_dependants      0
marital_status    0
income            0
dtype: int64

In [53]:
# Check for full-duplicates
df_customers_dups = df_customers[df_customers.duplicated()]

In [55]:
df_customers_dups

Empty DataFrame
Columns: [user_id, first_name, last_name, gender, state, age, date_joined, n_dependants, marital_status, income]
Index: []

The data-frame looks good.

6 - Combine your customer data with the rest of your prepared Instacart data. (Hint: Make sure the key columns are the same data type!)

In [59]:
# Importing ords_prods_merge
ords_prods_merge=pd.read_pickle(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Prepared_Data/aggregated_ords_prods_merge.pkl')

In [61]:
# check the data-types in the data frame ords_prods_merge
ords_prods_merge.dtypes

order_id                     int64
user_id                      int64
eval_set                    object
order_number                 int64
order_dow                    int64
order_hour_of_day            int64
days_since_prior_order     float64
first_order                   bool
product_id                   int64
add_to_cart_order            int64
reordered                    int64
Unnamed: 0_y                 int64
product_name                object
aisle_id                     int64
department_id                int64
prices                     float64
merge_info                category
price_range_loc             object
busiest_day                 object
Busiest_days                object
busiest_period_of_day       object
max_order                    int64
loyalty_flag                object
average_spend              float64
spending_flag               object
Customer_frequency         float64
frequency_flag              object
dtype: object

In [63]:
# Combining data-frames (df_customers with ords_prods_merge) using 'user_id' as key
df_cust_ords_prods_merged_df = pd.merge(ords_prods_merge, df_customers, on='user_id', how='inner')

7 - Ensure your notebook contains logical titles, section headings, and descriptive code comments.

In [66]:
# Checking the new data-frame
df_cust_ords_prods_merged_df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,...,frequency_flag,first_name,last_name,gender,state,age,date_joined,n_dependants,marital_status,income
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,2539329,1,prior,1,2,8,NaN,True,14084,2,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,2539329,1,prior,1,2,8,NaN,True,12427,3,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,2539329,1,prior,1,2,8,NaN,True,26088,4,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,2539329,1,prior,1,2,8,NaN,True,26405,5,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423

In [68]:
df_cust_ords_prods_merged_df.shape

(32404859, 36)

In [70]:
df_cust_ords_prods_merged_df.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,aisle_id,department_id,prices,max_order,average_spend,Customer_frequency,age,n_dependants,income
count,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.032876e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240485e+07,32404859.0,32404859.0,32404859.0
mean,1.710745e+06,1.029372e+05,1.714230e+01,2.738867e+00,1.342515e+01,1.110408e+01,2.559866e+04,8.352547e+00,5.895873e-01,2.560037e+04,7.119612e+01,9.919792e+00,7.790885e+00,3.305217e+01,7.790885e+00,1.039776e+01,49.46527,1.501896,99437.733295
std,9.872988e+05,5.946610e+04,1.753532e+01,2.090077e+00,4.246380e+00,8.779064e+00,1.408400e+04,7.127071e+00,4.919087e-01,1.408555e+04,3.821139e+01,6.281485e+00,4.241483e+00,2.515525e+01,7.347146e-01,7.131754e+00,18.485581,1.118865,43057.272542
min,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,18.0,0.0,25903.0
25%,8.559470e+05,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,1.354400e+04,3.000000e+00,0.000000e+00,1.354400e+04,3.100000e+01,4.000000e+00,4.200000e+00,1.300000e+01,7.378478e+00,6.000000e+00,33.0,1.0,67004.0
50%,1.711049e+06,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,2.530200e+04,6.000000e+00,1.000000e+00,2.530300e+04,8.300000e+01,9.000000e+00,7.400000e+00,2.600000e+01,7.811883e+00,8.000000e+00,49.0,2.0,96618.0
75%,2.565499e+06,1.543890e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,3.794700e+04,1.100000e+01,1.000000e+00,3.795100e+04,1.070000e+02,1.600000e+01,1.130000e+01,4.700000e+01,8.229228e+00,1.300000e+01,65.0,3.0,127912.0
max,3.421083e+06,2.062090e+05,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,4.968800e+04,1.450000e+02,1.000000e+00,4.969200e+04,1.340000e+02,2.100000e+01,2.500000e+01,9.900000e+01,2.320000e+01,3.000000e+01,81.0,3.0,593901.0

8 - Export to your folder

In [75]:
df_cust_ords_prods_merged_df.to_pickle(os.path.join(path, '02_Data', 'Prepared_Data', 'cust_ords_prods_merged.pkl'))

## Close