In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [8]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data'
# orders data
df_ords = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Prepared_Data/orders_wrangled_task4_04.csv', index_col = False)
# products data
df_prods = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/products.csv', index_col = False)

In [10]:
df_ords.describe()

,Unnamed: 0,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710541e+06,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552705e+05,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710541e+06,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421082e+06,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [12]:
#Createa a data-frame
df_test=pd.DataFrame()

In [14]:
# Create a mixed type column
df_test['mix']=['a', 'b', 1, True]

In [16]:
df_test.head()

    mix
0     a
1     b
2     1
3  True

In [26]:
# Check for mixed type columns
for col in df_test.columns.tolist():
  weird = (df_test[[col]].map(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_test[weird]) > 0:
    print (col)

mix

In [28]:
# Convert a column’s data type from numeric to string
df_test['mix'] = df_test['mix'].astype('str')

In [31]:
# Finding missing values
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [33]:
# Create a new Data-Frame containing only the missing values (condition isnull()=True)
df_nan=df_prods[df_prods['product_name'].isnull()==True]

In [35]:
df_nan

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

In [57]:
# Running expalantory analysis on the df_prods data-frame
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [59]:
# Finding the median for data-frame df_prods
df_prods['prices'].median()

7.1

In [69]:
# To find both upper and lower outliers
df_prods[(df_prods['prices'] > df_prods['prices'].mean() + 0.5 * df_prods['prices'].std()) |
                    (df_prods['prices'] < df_prods['prices'].mean() - 0.5 * df_prods['prices'].std())]

,product_id,product_name,aisle_id,department_id,prices
21554,21553,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0
33666,33664,2 % Reduced Fat Milk,84,16,99999.0

In [71]:
# Replacing the outliers (upper/lower) values with the median
df_prods = df_prods.replace({"prices": {14900.0: 7.1, 99999.0: 7.1}})

In [73]:
# checking the data-frame df_prods after replacing the outliers
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      7.682245
std    14343.717401     38.316774       5.850282      4.200159
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000     25.000000

In [37]:
df_prods.shape

(49693, 5)

In [39]:
# Create a new data-frame without missing values
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [41]:
df_prods_clean.shape

(49677, 5)

In [43]:
# looking for full duplicates within your dataframe:
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [45]:
df_dups

,product_id,product_name,aisle_id,department_id,prices
462,462,Fiber 4g Gummy Dietary Supplement,70,11,4.8
18459,18458,Ranger IPA,27,5,9.2
26810,26808,Black House Coffee Roasty Stout Beer,27,5,13.4
35309,35306,Gluten Free Organic Peanut Butter & Chocolate ...,121,14,6.8
35495,35491,Adore Forever Body Wash,127,11,9.9

In [47]:
# Checking the number of rows
df_prods_clean.shape

(49677, 5)

In [49]:
# Creating a new dta-frame that doesn't include diuplicates
df_prods_clean_no_dups = df_prods_clean.drop_duplicates()

In [51]:
# Checking the number of rows of the new data-fram after having removed the duplicates
df_prods_clean_no_dups.shape

(49672, 5)

In [53]:
# export data-frame free from duplicates as "products_checked_task4_05.csv"
df_prods_clean_no_dups.to_csv(os.path.join(path,'Prepared_Data','products_checked_task4_05.csv'))

In [77]:
# Checking data-frame df_ords for mixed type data
df_ords.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,0,2539329,1,prior,1,2,8,NaN
1,1,2398795,1,prior,2,3,7,15.0
2,2,473747,1,prior,3,3,12,21.0
3,3,2254736,1,prior,4,4,7,29.0
4,4,431534,1,prior,5,4,15,28.0

In [83]:
# Check for mixed type columns
for col in df_ords.columns.tolist():
  weird = (df_ords[[col]].map(type) != df_ords[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_ords[weird]) > 0:
    print (col)

In [85]:
df_ords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 8 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Unnamed: 0              int64
 1   order_id                int64
 2   user_id                 int64
 3   eval_set                object
 4   order_number            int64
 5   order_dow               int64
 6   order_hour_of_day       int64
 7   days_since_prior_order  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 208.8+ MB

In [87]:
# Check for missing value data-frame df_ords
df_ords.isnull().sum()

Unnamed: 0                     0
order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [93]:
df_ords_dup = df_ords[df_ords.duplicated()]

In [95]:
df_ords_dup

Empty DataFrame
Columns: [Unnamed: 0, order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order]
Index: []

In [97]:
# export data-frame free from duplicates as "products_checked_task4_05.csv"
df_ords.to_csv(os.path.join(path,'Prepared_Data','orders_checked_task4_05.csv'))