In [9]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [11]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data'

In [13]:
# Step 3 - Import orders_products_combined dataframe from pickle
df_ords_prod_comb = pd.read_pickle(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Prepared_Data/orders_products_combined.pkl')

In [15]:
# Step 4 - Check the shape of the imported dataframe
df_ords_prod_comb.shape

(32434489, 13)

In [18]:
# Import products data-frame
df_prods = pd.read_csv(os.path.join(path,'Prepared_Data','products_checked_task4_05.csv'), index_col = False)

In [20]:
# Checks the shape of the imported dataframes

In [22]:
# Check dataframe "df_ords_prod_comb" structure
df_ords_prod_comb.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,_merge
0,0,2539329,1,prior,1,2,8,NaN,True,196,1,0,both
1,0,2539329,1,prior,1,2,8,NaN,True,14084,2,0,both
2,0,2539329,1,prior,1,2,8,NaN,True,12427,3,0,both
3,0,2539329,1,prior,1,2,8,NaN,True,26088,4,0,both
4,0,2539329,1,prior,1,2,8,NaN,True,26405,5,0,both

In [24]:
# Check dataframe "df_prods" shape
df_prods.shape

(49672, 6)

In [26]:
# Check dataframe "df_prods" structure
df_prods.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices
0,0,1,Chocolate Sandwich Cookies,61,19,5.8
1,1,2,All-Seasons Salt,104,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,4,5,Green Chile Anytime Sauce,5,13,4.3

In [28]:
# Step 5 - Determine a suitable way to combine the orders_products_combined dataframe with your products data set

In [30]:
# The column "product_id" is a key identifier shared between these two data-frames, which makes a merge operation feasible.
# The type of merge to apply depends on the desired content of the final dataframe.
# Since we aim to retain only meaningful information that exists in both dataframes, an 'inner' merge is the most suitable option.
# This ensures that only rows with matching product_id values in both dataframes are included in the final result.

In [32]:
# Check columns in df_ords_prod_comb
print('Columns in df_ords_prod_comb:', df_ords_prod_comb.columns.tolist())

Columns in df_ords_prod_comb: ['Unnamed: 0', 'order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'first_order', 'product_id', 'add_to_cart_order', 'reordered', '_merge']

In [34]:
# Check columns in df_prods
print('Columns in df_prods:', df_prods.columns.tolist())

Columns in df_prods: ['Unnamed: 0', 'product_id', 'product_name', 'aisle_id', 'department_id', 'prices']

In [36]:
# The dataframe df_ords_prod_comb has already a column named "_merge" which conflicts with the default name of the indicator column.
# When using "indicator=True" pandas tries to create a new column called _merge, but it cannot overwrite an existing column with the
# same name. Consequently we need to use a custom name for the function.

In [38]:
# test merge without overwriting with custom name the for new merge column
pd.merge(
    df_ords_prod_comb,
    df_prods,
    on=['product_id'],
    how='inner',
    indicator='merge_info'  # Rename the indicator column
)

,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,merge_info
0,0,2539329,1,prior,1,2,8,NaN,True,196,1,0,both,195,Soda,77,7,9.0,both
1,0,2539329,1,prior,1,2,8,NaN,True,14084,2,0,both,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,0,2539329,1,prior,1,2,8,NaN,True,12427,3,0,both,12427,Original Beef Jerky,23,19,4.4,both
3,0,2539329,1,prior,1,2,8,NaN,True,26088,4,0,both,26089,Aged White Cheddar Popcorn,23,19,4.7,both
4,0,2539329,1,prior,1,2,8,NaN,True,26405,5,0,both,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,3421081,2977660,206209,prior,13,1,12,7.0,False,14197,5,1,both,14197,Tomato Paste,9,9,5.6,both
32404855,3421081,2977660,206209,prior,13,1,12,7.0,False,38730,6,0,both,38734,Brownie Crunch High Protein Bar,3,19,5.9,both
32404856,3421081,2977660,206209,prior,13,1,12,7.0,False,31477,7,0,both,31479,High Protein Bar Chunky Peanut Butter,3,19,4.2,both
32404857,3421081,2977660,206209,prior,13,1,12,7.0,False,6567,8,0,both,6567,Chocolate Peanut Butter Protein Bar,3,19,4.9,both
32404858,3421081,2977660,206209,prior,13,1,12,7.0,False,22920,9,0,both,22921,Roasted & Salted Shelled Pistachios,117,19,1.7,both

In [40]:
# The test was ok.
# The column _merge created from the previous exercise is of no use for the new data-frame df_ords_prod_comb.
# We should remove the column _merge after the new merge is completed.

In [42]:
# Merge data-frame df_prods and orders_products_combined
ords_prods_merge = df_ords_prod_comb.merge(
    df_prods, 
    on=['product_id'], 
    how='inner', 
    indicator='merge_info'
)

In [44]:
# Drop the column "_merge" from the previous merge
ords_prods_merge.drop('_merge', axis=1, inplace=True)

In [48]:
# Check after dropping the column
print(ords_prods_merge.columns)

Index(['Unnamed: 0_x', 'order_id', 'user_id', 'eval_set', 'order_number',
       'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'first_order', 'product_id', 'add_to_cart_order', 'reordered',
       'Unnamed: 0_y', 'product_name', 'aisle_id', 'department_id', 'prices',
       'merge_info'],
      dtype='object')

In [50]:
# Drop the column "'Unnamed: 0_x'" from the previous exercise
ords_prods_merge.drop('Unnamed: 0_x', axis=1, inplace=True)

In [52]:
# Check after dropping the column
print(ords_prods_merge.columns)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'first_order',
       'product_id', 'add_to_cart_order', 'reordered', 'Unnamed: 0_y',
       'product_name', 'aisle_id', 'department_id', 'prices', 'merge_info'],
      dtype='object')

In [58]:
# Check the output
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,merge_info
0,2539329,1,prior,1,2,8,NaN,True,196,1,0,195,Soda,77,7,9.0,both
1,2539329,1,prior,1,2,8,NaN,True,14084,2,0,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,prior,1,2,8,NaN,True,12427,3,0,12427,Original Beef Jerky,23,19,4.4,both
3,2539329,1,prior,1,2,8,NaN,True,26088,4,0,26089,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,prior,1,2,8,NaN,True,26405,5,0,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

In [62]:
# checking the shape
ords_prods_merge.shape

(32404859, 17)

In [68]:
# Confirm the results of the merge using the "merge_info" flag
ords_prods_merge['merge_info'].value_counts()

merge_info
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [72]:
# The resulting dataframe (after the merge) has 32,404,859 rows, and each of those rows have information found in both input data sets.

In [74]:
# Step 7 - Export the newly created dataframe as ords_prods_merge in a suitable format
ords_prods_merge.to_pickle(os.path.join(path, 'Prepared_Data', 'ords_prods_merge.pkl'))

# Close