In [6]:
# import libraries
import pandas as pd
import numpy as np
import os

In [8]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data'
# orders data
df_ords = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/orders.csv', index_col = False)
# products data
df_prods = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/products.csv', index_col = False)
# departments data
df_deps = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/departments.csv', index_col = False)

In [14]:
# Data Wrangling (per previous exercise)

In [16]:
# dropping column "eval_set" from orders data-frame
df_ords=df_ords.drop(columns = ['eval_set'])

In [18]:
# changing data type for order ID and user ID in orders data-frame
df_ords['order_id'] = df_ords['order_id'].astype('str')
df_ords['user_id'] = df_ords['user_id'].astype('str')

In [22]:
# transposing df_deps
df_deps_t=df_deps.T

In [24]:
# take first row of df_deps_t for the header
new_header = df_deps_t.iloc[0]

In [26]:
# copying df_deps_t from row 1 onward
df_deps_t_new = df_deps_t[1:]

In [30]:
# set the header row as the data-frame header
df_deps_t_new.columns = new_header

In [32]:
df_deps_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [34]:
data_dict = df_deps_t_new.to_dict('index')

In [36]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [40]:
# changing data type of order_id to non-numeric for analysis purposes
df_ords['order_id'] = df_ords['order_id'].astype('str')

In [42]:
# checking if the type changed doesn't appear in the stats
df_ords.describe()

       order_number     order_dow  order_hour_of_day  days_since_prior_order
count  3.421083e+06  3.421083e+06       3.421083e+06            3.214874e+06
mean   1.715486e+01  2.776219e+00       1.345202e+01            1.111484e+01
std    1.773316e+01  2.046829e+00       4.226088e+00            9.206737e+00
min    1.000000e+00  0.000000e+00       0.000000e+00            0.000000e+00
25%    5.000000e+00  1.000000e+00       1.000000e+01            4.000000e+00
50%    1.100000e+01  3.000000e+00       1.300000e+01            7.000000e+00
75%    2.300000e+01  5.000000e+00       1.600000e+01            1.500000e+01
max    1.000000e+02  6.000000e+00       2.300000e+01            3.000000e+01

In [50]:
# rename column day of the week in orders data-frame
df_ords.rename(columns = {'order_dow' : 'order_day_of_the_week'}, inplace = True)

In [56]:
df_ords.columns

Index(['order_id', 'user_id', 'order_number', 'order_day_of_the_week',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

In [58]:
# finding busiest hour
df_ords['order_hour_of_day'].value_counts(dropna = True)

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

In [62]:
# Determine the meaning behind a value of 4 in the "department_id" column within the data-frame df_prods
print(data_dict.get('4'))

{'department': 'produce'}

In [64]:
# creating the subset
df_prods_breakfast = df_prods.loc[df_prods['department_id'] == 14]

In [66]:
# checking result
df_prods_breakfast.head()

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6

In [68]:
# creating "dinner party" subset
df_dinner_party = df_prods.loc[df_prods['department_id'].isin([5,7,12,20])]

In [74]:
df_dinner_party.head(25)

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
19,20,Pomegranate Cranberry & Aloe Vera Enrich Drink,98,7,6.0
22,23,Organic Turkey Burgers,49,12,8.2
34,35,Italian Herb Porcini Mushrooms Chicken Sausage,106,12,15.1
38,39,Daily Tangerine Citrus Flavored Beverage,64,7,12.5
39,40,Beef Hot Links Beef Smoked Sausage With Chile ...,106,12,22.5
43,44,Sparkling Raspberry Seltzer,115,7,12.2
48,49,Vegetarian Grain Meat Sausages Italian - 4 CT,14,20,10.1
51,52,Mirabelle Brut Rose,134,5,14.4
52,53,Whole Leaf Pure Aloe With Lemon Juice,98,7,4.7
61,62,Premium Deli Oven Roasted Turkey Breast,96,20,14.6
68,69,NaN,26,7,11.8
72,73,Jasmine Tea Unfiltered Ginger Ale,77,7,8.3
73,74,Artisan Chick'n & Apple Sausage,14,20,3.0
81,82,All Natural 100% Apple Juice,98,7,6.4
83,84,Lamb Shank,7,12,24.3
84,85,Soppressata Piccante,96,20,8.9
86,87,Classics Earl Grey Tea,94,7,9.1
96,97,Organic Chamomile Lemon Tea,94,7,8.4
108,109,Grape Leaf Hummus Wrap,13,20,7.1
118,119,Chardonnay Paso Robles,62,5,5.5

In [78]:
# Find the number of rows for the last data-frame created
df_dinner_party.shape

(7650, 5)

In [84]:
# Find info about customer with user_id 1
df_user1=df_ords.loc[df_ords['user_id'] == '1']
df_user1

,order_id,user_id,order_number,order_day_of_the_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
5,3367565,1,6,2,7,19.0
6,550135,1,7,1,9,20.0
7,3108588,1,8,1,14,14.0
8,2295261,1,9,1,16,0.0
9,2550362,1,10,4,8,30.0
10,1187899,1,11,4,8,14.0

In [86]:
# Stats about user's behaviour
df_user1.describe()

,order_number,order_day_of_the_week,order_hour_of_day,days_since_prior_order
count,11.000000,11.000000,11.000000,10.000000
mean,6.000000,2.636364,10.090909,19.000000
std,3.316625,1.286291,3.477198,9.030811
min,1.000000,1.000000,7.000000,0.000000
25%,3.500000,1.500000,7.500000,14.250000
50%,6.000000,3.000000,8.000000,19.500000
75%,8.500000,4.000000,13.000000,26.250000
max,11.000000,4.000000,16.000000,30.000000

In [10]:
# export orders data-frame as "orders.wrangled.csv" 
df_ords.to_csv(os.path.join(path,'Prepared_Data','orders_wrangled_task4_04.csv'))

In [11]:
# export departments data-frame as "departments.wrangled.csv" 
df_deps.to_csv(os.path.join(path,'Prepared_Data','departments_wrangled_task4_04.csv'))